In [1]:
!pip install faiss-cpu
!pip install sentence-transformers

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.0/27.0 MB 46.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 171.5/171.5 kB 4.1 MB/s eta 0:00:00
  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
  Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (731.7 MB)
  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
  Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
  Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
  Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
  Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
  Using cached nvidia_nccl_cu12-2.19.3-py3-none-manyli

In [2]:
import pandas as pd
pd.set_option('display.max_colwidth', 100)

In [3]:
df = pd.read_csv("/content/drive/MyDrive/ExtraCredit/smpl.csv")
df.shape

(8, 2)

In [4]:
df

text  \
0                                        Meditation and yoga can improve mental health   
1                     Fruits, whole grains and vegetables helps control blood pressure   
2                                    These are the latest fashion trends for this week   
3                                    Vibrant color jeans for male are becoming a trend   
4                                                   The concert starts at 7 PM tonight   
5                      Navaratri dandiya program at Expo center in Mumbai this october   
6                                    Exciting vacation destinations for your next trip   
7  Maldives and Srilanka are gaining popularity in terms of low budget vacation places   

  category  
0   Health  
1   Health  
2  Fashion  
3  Fashion  
4    Event  
5    Event  
6   Travel  
7   Travel

In [5]:
from sentence_transformers import SentenceTransformer

In [6]:
encdr = SentenceTransformer("all-mpnet-base-v2")
vctrs = encdr.encode(df.text)

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:88: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.6k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/571 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

1_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [7]:
vctrs.shape

(8, 768)

In [8]:
dm = vctrs.shape[1]
dm

768

In [9]:
import faiss
idx = faiss.IndexFlatL2(dm)

In [10]:
idx.add(vctrs)
idx

<faiss.swigfaiss_avx2.IndexFlatL2; proxy of <Swig Object of type 'faiss::IndexFlatL2 *' at 0x7e2ca0087d50> >

In [11]:
# search_query = "I want to buy a polo t-shirt"
search_query = "An apple a day keeps the doctor away"
vec = encdr.encode(search_query)
vec.shape

(768,)

In [12]:
vec

array([ 1.77043006e-02,  7.70549104e-02, -1.25192972e-02, -1.39330723e-03,
        5.92105323e-03, -1.42679447e-02, -4.72583547e-02,  3.91948037e-03,
        4.41601165e-02,  3.09807677e-02,  9.15983170e-02,  2.02602837e-02,
       -2.16005053e-02,  1.33207971e-02, -4.14276049e-02,  4.16395180e-02,
        4.37019169e-02,  6.06420450e-03,  2.21781414e-02, -1.94715392e-02,
       -3.44190747e-02,  3.79219651e-02,  5.27903717e-03,  2.22010966e-02,
       -1.11636585e-02, -2.53351070e-02,  7.79388398e-02,  3.47347856e-02,
        1.20056644e-02, -6.52653798e-02, -4.83940691e-02, -3.03445645e-02,
       -6.99562728e-02, -2.53461283e-02,  1.78119080e-06,  1.50222201e-02,
        2.15191916e-02,  2.21124683e-02, -8.38034377e-02,  3.70957679e-03,
       -2.21118182e-02, -8.53062496e-02,  6.44908345e-04,  1.62597932e-02,
       -1.88165568e-02,  3.99218015e-02, -3.13138887e-02,  2.47449800e-02,
       -7.98757654e-03,  6.11144453e-02, -1.47846416e-02,  4.10558605e-05,
        1.20446552e-02,  

In [13]:
import numpy as np
svec = np.array(vec).reshape(1,-1)
svec.shape

(1, 768)

In [14]:
idx.search(svec,k=2)

(array([[1.3433158, 1.7125273]], dtype=float32), array([[1, 0]]))

In [16]:
dstncs, I = idx.search(svec, k=2)
dstncs

array([[1.3433158, 1.7125273]], dtype=float32)

In [17]:
I

array([[1, 0]])

In [18]:
I.tolist()

[[1, 0]]

In [19]:
row_indices = I.tolist()[0]
row_indices

[1, 0]

In [20]:
df.loc[row_indices]

text category
1  Fruits, whole grains and vegetables helps control blood pressure   Health
0                     Meditation and yoga can improve mental health   Health

from matplotlib import pyplot as plt
import seaborn as sns
_df_0.groupby('text').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

In [21]:
search_query

'An apple a day keeps the doctor away'